[font]
size = 16

normal.family = "MesloLGS Nerd Font Mono"

# [font.bold]
# family = "MesloLGS Nerd Font Mono"
# style = "Bold"
#
# [font.bold_italic]
# family = "MesloLGS Nerd Font Mono"
# style = "BoldItalic"
#
# [font.italic]
# family = "MesloLGS Nerd Font Mono"
# style = "Italic"
#
# [font.normal]
# family = "MesloLGS Nerd Font Mono"
# style = "Regular"

[font.offset]
x = 0
y = 2
